/***
This file is autogenerated, please do not edit it.
To generate an updated version, please run `yarn genreg`

If you register your helper with this index, it can be referenced more easily.

e.g. without registering

  import fetcher from 'lib/helpers/fetcher
  import poster from 'lib/helpers/poster

e.g. with registering

  import { fetcher, poster } from 'lib/helpers'
*/

export { default as fakeEvent } from './fake-event';
export { default as generateId } from './generate-id';
export { default as getTrueItemCount } from './get-true-item-count';
export { default as handleFormValidation } from './handle-form-validation';