app:
  name: My App
commands:
  atom:
    type: scaffold
    outputPath: ./components/atoms
    use: foxys-own
    substitute:
      - string: prefix
        default: Atom
      - string: type
        default: Component
  molecule:
    type: scaffold
    outputPath: ./components/molecules
    use: foxys-own
    substitute:
      - string: prefix
        default: Molecule
      - string: type
        default: Component
  organism:
    type: scaffold
    outputPath: ./components/organisms
    use: foxys-own
    substitute:
      - string: prefix
        default: Organism
      - string: type
        default: Component
  page:
    type: scaffold
    outputPath: ./pages
    use: foxys-own
    substitute:
      - string: prefix
        default: Page
      - string: type
        default: Page
  input:
    type: scaffold
    outputPath: ./components/inputs
    use: foxys-own
    substitute:
      - string: prefix
        default: Input
      - string: type
        default: Component
modules:
  scaffold:
    foxys-own: 2.0.0
