import React, { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import { useAuth } from '../lib/context/auth-context';
import { useRouter } from 'next/router';
import { User } from '../lib/types/user';

const Home: NextPage = () => {
  const router = useRouter();
  const [currentUser, setCurrentUser] = useState<User>();

  const auth = useAuth();

  useEffect(() => {
    // Check if a user is logged in
    // If not, redirect to /login
    const user = auth?.getUser();
    if (!user?.email) {
      router.push('/login');
    } else {
      setCurrentUser(user);
    }
  }, [auth?.getUser, router]);

  if (currentUser) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Welcome {currentUser.displayName}</h1>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    );
  }
  return <div>Loading...</div>;
};

export default Home;
