import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import { useInput } from '../lib/hooks';
import { useAuth } from '../lib/context/auth-context';

const Login: NextPage = () => {
  const { user, register } = useAuth();

  const email = useInput('');
  const password = useInput('');
  const name = useInput('');

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    register(email.value, password.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Register</h1>
        <form onSubmit={handleSubmit}>
          <label>
            Email:
            <input type="email" name="email" {...email} />
          </label>
          <label>
            Password:
            <input type="password" name="password" {...password} />
          </label>
          <label>
            Name:
            <input type="text" name="name" {...name} />
          </label>
          <button type="submit">Sign me up!</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Login;
