import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import FcProps from 'lib/types/fc-props';

import styles from './center.module.scss';

const CenterTemplate: NextPage<FcProps> = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>{children}</main>
    </div>
  );
};

export default CenterTemplate;
