import React, { useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useAuth } from 'lib/context/auth-context';
import { useRouter } from 'next/router';
import FcProps from 'lib/types/fc-props';

import styles from './main.module.scss';
import { User } from 'lib/types/user';
import AppHeader from 'components/layout/app-header';

const MainTemplate: NextPage<FcProps> = ({ children }) => {
  const router = useRouter();
  const auth = useAuth();

  const [user, setUser] = React.useState<User | undefined>(undefined);

  useEffect(() => {
    const getUser = auth?.getUser();
    setUser(getUser);
    if (!getUser?.email) {
      router.push('/login');
    }
  }, []);

  if (user) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AppHeader user={user} />
        <main className={styles.main}>{children}</main>
        <footer className={styles.footer}>Nothing here yet</footer>
      </div>
    );
  }
  return <div>Loading...</div>;
};

export default MainTemplate;
