import React, { useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useAuth } from 'lib/context/auth-context';
import { useRouter } from 'next/router';
import FcProps from 'lib/types/fc-props';

import styles from './main.module.scss';
import { User } from 'lib/types/user';

const MainTemplate: NextPage<FcProps> = ({ children }) => {
  const router = useRouter();
  const auth = useAuth();

  const [user, setUser] = React.useState<User | undefined>(undefined);

  useEffect(() => {
    const getUser = auth?.getUser();
    // Check if a user is logged in
    // If not, redirect to /login
    setUser(getUser);
    if (!getUser?.email) {
      router.push('/login');
    }
  }, []);

  if (user) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
          <h1 className={styles.title}>What&rsquo;s in the box?</h1>
          <span className={styles.subtitle}>
            Track your stuff during a move
          </span>
        </header>
        <main className={styles.main}>{children}</main>

        <footer className={styles.footer}>Nothing here yet</footer>
      </div>
    );
  }
  return <div>Loading...</div>;
};

export default MainTemplate;
