import React, { useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useAuth } from 'lib/context/auth-context';
import { useRouter } from 'next/router';
import FcProps from 'lib/types/fc-props';

import styles from './main.module.scss';
import { User } from 'lib/types/user';

const MainTemplate: NextPage<FcProps> = ({ children }) => {
  const router = useRouter();
  const auth = useAuth();

  const [user, setUser] = React.useState<User | undefined>(undefined);

  useEffect(() => {
    const getUser = auth?.getUser();
    // Check if a user is logged in
    // If not, redirect to /login
    setUser(getUser);
    if (!getUser?.email) {
      router.push('/login');
    }
  }, [auth, router]);

  if (user?.email) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>{children}</main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    );
  }
  return <div>Loading...</div>;
};

export default MainTemplate;
